In [65]:
import pandas as pd
import numpy as np

In [66]:
# Weekday
PATH = "/media/sf_BLOB_STORAGE/Roster/Weekdays/Copy of Drivers and Rosters MON 01.03 to TUE 02.03.xlsx"
PATH = "/media/sf_BLOB_STORAGE/Roster/Weekdays/Copy of Drivers and Rosters THU 08.04 to FRI 09.04.xlsx"
df = pd.read_excel(PATH)

In [79]:
df.iloc[:,0].str.lower()

# When Visy is same column as 
if df[df.iloc[:,0].str.lower().eq("visy")].any(True).values:
    visyidx = df[df.iloc[:,0].str.lower().eq("visy")].index[0]
    
    if df[df.iloc[:,0].str.lower().eq("university")].any(True).values:
        uosidx = df[df.iloc[:,0].str.lower().eq("university")].index[0]
#       Plus 1 to capture only Rocky Li
        visy_df = df.iloc[visyidx+1:uosidx]
    
visy_df
# df.loc[df.iloc[:,0] == "day runs"]
# lookup for Word => Day Runs 
# df[df.iloc[:,0].str.lower().eq("day runs")].index[0]
# .eq("visy")

    

#     df[].index[0]
# Identify Visy Exist
# condition 1 - Col 1 has visy / Col 2 is nan / col 3 is nan

# condition 2 ricky li / john justice are definitly in visy

      NIGHT RUNS    THURSDAY Unnamed: 2 2021-04-08 00:00:00
28      RICKY LI      NIWPR1    XPL 658                 NaN
29  JOHN JUSTICE  NIWPR2/CBK   BY 46 TO                 NaN

In [68]:
df

,NIGHT RUNS,THURSDAY,Unnamed: 2,2021-04-08 00:00:00
0,ADONIS AKL,RLE,CL 98 LU,NaN
1,PAUL NEVIN,BR2,CJ 65 PS,NaN
2,KEVEN SHEATHER,RL8,XN 62 UD,NaN
3,PETER DINH,RED,XN 19 IN,NaN
4,PETER DINH,RLR,XN 19 IN,NaN
5,ALAN WALDEN,RLC,XN 65 IJ,NaN
6,DAY RUNS,FRIDAY,NaN,2021-04-09 00:00:00
7,JOHNNY RUHR,BR1,XN 75 OS,NaN
8,TAIT MITCHELL,BR3,XN 06 OJ,NaN
9,GARY ROBERTS,RL1,CN 41 XN,NaN
10,ALBERT DO,RL2,XN 23 KQ,NaN
11,FEKE TUPOU,RL4,XN 81 VB,NaN
12,LOU MOYLAN,RL5,CG 06 UT,NaN
13,JOHN FIELD,RL6,XN 62 UD,NaN
14,ZAC DEAN,RL7,XN 44 QZ,NaN
15,TOM TE TURE,RL9,BL 82 AG,NaN
16,VICTOR SINGH,RLD,CL 02 TB,NaN
17,LEIGH BURGESS,RLH,XN 19 IN,NaN
18,PHIL LIU,RLI,XN 13 KR,NaN
19,LUKE BOLAND,RLJ,XN 10 HU,NaN
20,DAVID RIGHT,HOOK/RLK,XN23UV/XN71FD,NaN
21,NEIL WHITE,RLP,CH 32 FV,NaN
22,BEN EDWARDS,SWG,XN 72 MK,NaN
23,GABBY HEWITT,HYG,CF 48 ED,NaN
24,JOHN TUBUAITUA,DOY,XN 65 IJ,NaN
25,JULIAN TAURIMA,FL2,XN 52 IJ,NaN
26,CHRIS BAILEY,FLG,XN 25 GD,NaN
27,VISY,NaN,NaN,NaN
28,RICKY LI,NIWPR1,XPL 658,NaN
29,JOHN JUSTICE,NIWPR2/CBK,BY 46 TO,NaN
30,UNIVERSITY,NaN,NaN,NaN
31,ROB WARD,UOS,XN 76 VB,NaN
32,NATHAN BRACEY,UOS/CMD/SWG,CQ 64 LO,NaN
33,NaN,NaN,NaN,NaN
34,B.LOCKE,RAY HEARN,NaN,NaN
35,SICK,A/LEAVE,NaN,NaN
36,SPARE TRUCKS,(CHECK WHAT NIGHT TRUCKS ARE BACK),NaN,NaN
37,R/L SINGLE,CG 94 KY,CF71JM But has c/b on,NaN
38,R/L BOGEY,AB 40 PW,CBB804/CG06UT,XN 80 YD
39,OUT OF SERVICE,NaN,NaN,NaN
40,F/L,NaN,NaN,NaN
41,R/L BOGEY,NaN,NaN,NaN
42,R/L SINGLE,XN 97 FC,NaN,NaN